% focus script
filepath = '/home/physics/QHYtest/COtest.txt';
Period = Q.expTime;
f= figure;
ax=axes('parent',f);
h=imagesc(ax);
T =timer( ...
    'ExecutionMode', 'fixedSpacing',...
    'StartDelay',Period, ...
    'Period', Period, ...
    'StartFcn', 'start_sequence_take(Q)',...
    'TimerFcn', 'QHYfun.focus_poll(Q,h);',...
    'StopFcn', 'stop_sequence_take(Q)' ...
);
start(T)
